version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: map-editor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mapdata
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: map-editor-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/mapdata
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: unless-stopped

  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: map-editor-tileserver
    volumes:
      - ./tiles:/data
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: map-editor-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - backend
      - tileserver
    restart: unless-stopped